services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    command: npm run dev
    depends_on:
      - ml-model

  ml-model:
    build: ./ml-model
    ports:
      - "8000:8000"
    volumes:
      - ./ml-model:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "ml_app:app", "--host", "0.0.0.0", "--port", "8000"]